### ISSUE TITLE
extract cable title

### ISSUE THREAD

**Issue by elishowk** [elishowk/cablegate_semnet#3]
ex :
....
<div class='pane big'>

<h3>Viewing cable 09DAKAR1069, CONFLICTING MESSAGES ABOUT WADE'S MONUMENT</h3>

...

**Comment by heuer** [comment]
Hi there, maybe you don't want to switch your parser at this stage, but cablemap https://github.com/heuer/cablemap gives access to the subject of a cable. It does not rely on the information provided by Wikileaks since the subjects are often incomplete, but extracts the cable's subject from the cable's content.

```
>>> from cablemap.core import cable_from_html
>>> from cablemap.core.utils import cable_page_by_id
>>> page = cable_page_by_id('09BERLIN1167'')
>>> cable = cable_from_html(page)
>>> cable.subject
u'DATA PRIVACY TRUMPS SECURITY: IMPLICATIONS OF A FDP VICTORY ON COUNTERTERRORISM COOPERATION'
```

"cable_page_by_id" fetches the cable from the Internet, but can also use "cable = cable_from_html(page)" or "cable_from_file" with an offline version of Cablegate

**Comment by elishowk** [comment]
Thanks, but I just set up a simple regexp extraction on the <H3> tag containing containing, for example : "Viewing cable 09DAKAR1069, CONFLICTING MESSAGES ABOUT WADE'S MONUMENT"
That works fine enough.

**Comment by heuer** [comment]
No worries. 

For the record, here an example where Wikileaks provides an incomplete subject: "02ROME1196": "AS PREDICTED, ITALY’S HUMAN RIGHTS REPORT"

While Cablemap returns the complete subject:

```
>>> cable_from_html(cable_page_by_id('02ROME1196')).subject
u'AS PREDICTED, ITALY\u2019S HUMAN RIGHTS REPORT GENERATES FODDER FOR DOMESTIC POLITICAL MILLS'
```

**Comment by elishowk** [comment]
You're right !
Unfortunately I'm too late on my other features to redesign extraction...
I keep following you're module.
